### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by martindzejky** [jean-smaug/babel-plugin-search-and-replace#6]
Hello! First of all thanks for making this plugin, it really helped us in our project. However, it is quite hard to use because you don't provide any documentation for it. For instance, it took me 2 days and a good look into your source code to figure out that if you use `search: "string"`, it only replaces string literals that match the whole search value.

For example, with this configuration:

```
rules: [{
  search: 'foo',
  replace: 'baz',
}]
```

this string is successfully replaced:

```
string = "foo"
```

**but not** this string:

```
string = "foo bar"
```

You have to use the regex variant for this, i. e.:

```
rules: [{
  search: /foo/,
  replace: 'baz',
}]
```

I don't know if this is a bug, but if it isn't, you should at least mention this in the README file. Otherwise, I spend a lot of hours wondering why the plugin does not replace all of my strings.

**Comment by jean-smaug** [comment]
Hey man.

Indeed it's a strict equal comparison when using a string for the search.

I will update it.

I didn't write this plugin for a personal usage. It was to experiment how the babel AST was working.

So I will update it to make the "string version" accept strings that doesn't match exactly the searched value.

🎻

**Comment by klwemu** [comment]
As I can see, Regex is still not working.
